docker_image:
  - condaforge/linux-anvil-cuda:10.1
  - condaforge/linux-anvil-cuda:10.0
  - condaforge/linux-anvil-cuda:9.2
CUDA_VER:
  - 10.1
  - 10.0
  - 9.2
zip_keys:
  - - CUDA_VER
    - docker_image
