# # cuda 8.0, gcc 5.4, cudnn 7.1
# # cuda 9.0, gcc 5.4, cudnn 7.3
# # cuda 9.2, gcc 7.3, cudnn 7.3
# # cuda 10.0, gcc 7.3, cudnn 7.3
# c_compiler_version:   # [linux]
#   - 7.3               # [linux]
# cxx_compiler_version: # [linux]
#   - 7.3               # [linux]
cuda_compiler: nvcc
cuda_compiler_version:
  - 9.2
  #- 10.0
  # - 10.1
  #- 10.2
  #- 11.0