docker_image:
  - condaforge/linux-anvil-cuda:10.1
  - condaforge/linux-anvil-cuda:10.0
  - condaforge/linux-anvil-cuda:9.2
cuda_compiler_version:
  - 10.1
  - 10.0
  - 9.2
zip_keys:
  - - cuda_compiler_version
    - docker_image
