{% set name = "nvcc" %}
{% set number = 8 %}

package:
  name: "{{ name }}"

build:
  number: {{ number }}
  skip: true  # [osx or cuda_compiler_version == "None"]

outputs:
  - name: "{{ name }}_{{ target_platform }}"
    version: "{{ cuda_compiler_version }}"
    number: {{ number }}
    script: install_nvcc.sh   # [linux]
    script: windows/install_nvcc.bat  # [win]
    build:
      ignore_run_exports:
        - libgcc-ng
      run_exports:
        strong:
          - cudatoolkit {{ cuda_compiler_version }}|{{ cuda_compiler_version }}.*
          - __glibc >=2.17  # [linux and cuda_compiler_version == "11.0"]
    requirements:
      host:
        # Needed to symlink libcuda into sysroot libs.
        # FIXME: nvcc 9.* and 10.* don't work with GCC 9.
        #        Adding custom GCC versions via conda_build_config.yaml fails
        #        due to https://github.com/conda/conda-build/issues/3974
        #        => use hardcoded compiler package names to workaround that.
        - {{ compiler("c") }}    # [not (linux64 and (cuda_compiler_version or "").startswith(("9.", "10.")))]
        - gcc_linux-64 7         # [linux64 and (cuda_compiler_version or "").startswith(("9.", "10."))]
        - sysroot_linux-64 2.17  # [linux and cuda_compiler_version == "11.0"]
        - __glibc >=2.17         # [linux and cuda_compiler_version == "11.0"]
      run:
        - sysroot_linux-64 2.17  # [linux and cuda_compiler_version == "11.0"]
        - __glibc >=2.17         # [linux and cuda_compiler_version == "11.0"]
    test:
      requires:
        - {{ compiler("c") }}    # [not (linux64 and (cuda_compiler_version or "").startswith(("9.", "10.")))]
        - gcc_linux-64 7         # [linux64 and (cuda_compiler_version or "").startswith(("9.", "10."))]
        # Host code is forwarded to a C++ compiler
        - {{ compiler("cxx") }}  # [not (linux64 and (cuda_compiler_version or "").startswith(("9.", "10.")))]
        - gxx_linux-64 7         # [linux64 and (cuda_compiler_version or "").startswith(("9.", "10."))]
        - sysroot_linux-64 2.17  # [linux and cuda_compiler_version == "11.0"]
      files:
        - test.cu
        - test_nvcc.sh  # [linux]
        - windows\test_nvcc.bat  # [win]
      commands:
        - bash test_nvcc.sh  # [linux]
        - windows\test_nvcc.bat  # [win]
    about:
      home: https://github.com/conda-forge/nvcc-feedstock
      license: BSD-3-Clause
      license_file: LICENSE.txt
      summary: A meta-package to enable the right nvcc.

about:
  home: https://github.com/conda-forge/nvcc-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A meta-package to enable the right nvcc.

extra:
  recipe-maintainers:
    - dillon-cullinan
    - isuruf
    - jakirkham
    - kkraus14
    - mike-wendt
    - raydouglass
