travis:
  secure:
    BINSTAR_TOKEN: OxEDP63i8IB6KqR8Siw1TlkklGY2bWjTVh9nrYOlvj213j2/NRHyrD7dExTV2DLJ+cgPN1wXis1zmQCs+zJus+gPFDlXy/a01egMy/jxf3TuDH7yCuE9eirbSsArPDP/nAEJwNdokQ+DKjOyblFyBqTcpyZnXffyIOAitC8R8JCuF72gbFGE1Xo5ur3CyzBnpm6zYK27y+KHLaOYVveQgvJ4v2v3VLO4sQ7UYAhCkiY9nEEdUMDjE7zNREZZkQ8TX1hE/UK3jQ9FVGvZLZuGKgLMlmb/dbkZHRM9cy5Mk6s15XObv2MlhF7+IxAqJC9IlgD6gr9hQFwzM4mK46IhsjvV+y/zKLTmggJMaeBnWeADWLuCIqwN8zHgJav58RRtwmcu4RuuiEIEl+xtcGl2i4cFCDYuJVLJ73o862ZOoReRMVVoeYac3MFJIszDsP5UWJw5/cq4Ro1aOMaoqZHtIhnfH+Fz5qw9o2ImUdFRtfNzwca4QFM+QNhkLA2cAlHm/NdJS3mT8QSombEbQ3AaWMPbuXnlyrn+o7mlEYRRG8SrjScJN/UoiLRK7R1eVU3x71rSbMmf3qLTJz5zHyxgSy9YPv22G9+B/H8lw03w1YdzsoxKOOlpDycwmuwonBlw+7PygXIQMmE4p8+KtMO48/uuFLdqatDoHmNl1h6l0kg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
